package config

import (
	"errors"
	"fmt"
	"net"
	"net/url"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"omnora/internal/access"
	"omnora/internal/domain"
)

// ErrPublicURLRequired means business routes are enabled but OMNORA_PUBLIC_URL
// has not been configured yet. The process may still start and serve
// /healthz+/readyz; business handlers stay fail-closed until the operator sets
// the public origin after the deployment address is known.
var ErrPublicURLRequired = errors.New("OMNORA_PUBLIC_URL is required when a business route is enabled")

type Config struct {
	HTTP              HTTPConfig
	MCP               MCPConfig
	Log               LogConfig
	Database          DatabaseConfig
	Initialization    InitializationConfig
	Secrets           SecretConfig
	Storage           StorageConfig
	Update            UpdateConfig
	Routes            access.RouteGroups
	RouteEnvOverrides map[domain.RouteGroup]bool
}

// MCPConfig contains the network boundary for the standard Streamable HTTP
// endpoint. It is intentionally separate from the browser HTTP trust policy:
// MCP clients authenticate with AI Tokens and may be non-browser callers.
type MCPConfig struct {
	AllowedHosts   []string
	AllowedOrigins []string
	MaxBodyBytes   int64
}

type StorageConfig struct {
	ManagedDir           string
	PredeclaredMountRoot string
}

type UpdateConfig struct {
	StateDir        string
	MaxPackageBytes int64
}

type HTTPConfig struct {
	Addr                    string
	PublicURL               string
	AllowedHosts            []string
	AllowedOrigins          []string
	TrustedProxyCIDRs       []*net.IPNet
	AllowInsecurePublicHTTP bool
}

type LogConfig struct {
	Format string
	Level  string
}

type DatabaseConfig struct {
	Path        string
	BusyTimeout time.Duration
}

type InitializationConfig struct {
	Token    string
	TTL      time.Duration
	LogToken bool
}

type SecretConfig struct {
	TOTPEncryptionKey string
	// AuditHMACKey is the stable deployment secret used for domain-separated
	// audit identifiers. It is intentionally not generated by the Go process;
	// the container entrypoint persists it before startup.
	AuditHMACKey string
}

func LoadEnv() (Config, error) {
	cfg := Config{
		HTTP: HTTPConfig{
			Addr: "127.0.0.1:8080",
		},
		MCP: MCPConfig{
			MaxBodyBytes: 1 << 20,
		},
		Log: LogConfig{
			Format: "text",
			Level:  "info",
		},
		Database: DatabaseConfig{
			BusyTimeout: 5 * time.Second,
		},
		Initialization: InitializationConfig{
			TTL: 30 * time.Minute,
		},
		Storage: StorageConfig{
			ManagedDir:           "/srv/omnora/managed",
			PredeclaredMountRoot: "/mnt/omnora",
		},
		Update: UpdateConfig{
			MaxPackageBytes: 512 << 20,
		},
		Routes:            access.DefaultRouteGroups(),
		RouteEnvOverrides: map[domain.RouteGroup]bool{},
	}

	if value := strings.TrimSpace(os.Getenv("OMNORA_HTTP_ADDR")); value != "" {
		cfg.HTTP.Addr = value
	}
	if _, _, err := net.SplitHostPort(cfg.HTTP.Addr); err != nil {
		return Config{}, fmt.Errorf("OMNORA_HTTP_ADDR must be host:port: %w", err)
	}
	cfg.HTTP.PublicURL = strings.TrimSpace(os.Getenv("OMNORA_PUBLIC_URL"))
	cfg.HTTP.AllowInsecurePublicHTTP = envTruthy("OMNORA_ALLOW_INSECURE_PUBLIC_HTTP")
	var err error
	cfg.HTTP.AllowedHosts, err = parseCSVEnv("OMNORA_ALLOWED_HOSTS")
	if err != nil {
		return Config{}, err
	}
	cfg.HTTP.AllowedOrigins, err = parseCSVEnv("OMNORA_ALLOWED_ORIGINS")
	if err != nil {
		return Config{}, err
	}
	cfg.HTTP.TrustedProxyCIDRs, err = parseCIDRsEnv("OMNORA_TRUSTED_PROXY_CIDRS")
	if err != nil {
		return Config{}, err
	}
	cfg.MCP.AllowedHosts, err = parseCSVEnv("OMNORA_MCP_ALLOWED_HOSTS")
	if err != nil {
		return Config{}, err
	}
	cfg.MCP.AllowedOrigins, err = parseCSVEnv("OMNORA_MCP_ALLOWED_ORIGINS")
	if err != nil {
		return Config{}, err
	}
	if value := strings.TrimSpace(os.Getenv("OMNORA_MCP_MAX_BODY_BYTES")); value != "" {
		maxBodyBytes, parseErr := strconv.ParseInt(value, 10, 64)
		if parseErr != nil || maxBodyBytes <= 0 {
			return Config{}, fmt.Errorf("OMNORA_MCP_MAX_BODY_BYTES must be a positive integer")
		}
		cfg.MCP.MaxBodyBytes = maxBodyBytes
	}
	if value := strings.TrimSpace(os.Getenv("OMNORA_LOG_FORMAT")); value != "" {
		cfg.Log.Format = strings.ToLower(value)
	}
	switch cfg.Log.Format {
	case "text", "json":
	default:
		return Config{}, fmt.Errorf("OMNORA_LOG_FORMAT must be text or json")
	}
	if value := strings.TrimSpace(os.Getenv("OMNORA_LOG_LEVEL")); value != "" {
		cfg.Log.Level = strings.ToLower(value)
	}
	switch cfg.Log.Level {
	case "debug", "info", "warn", "error":
	default:
		return Config{}, fmt.Errorf("OMNORA_LOG_LEVEL must be debug, info, warn, or error")
	}
	cfg.Database.Path = strings.TrimSpace(os.Getenv("OMNORA_DB_PATH"))
	if cfg.Database.Path != "" {
		cfg.Update.StateDir = filepath.Join(filepath.Dir(cfg.Database.Path), "updates")
	}
	if value := strings.TrimSpace(os.Getenv("OMNORA_UPDATE_DIR")); value != "" {
		cfg.Update.StateDir = value
	}
	if value := strings.TrimSpace(os.Getenv("OMNORA_UPDATE_MAX_PACKAGE_BYTES")); value != "" {
		maxBytes, parseErr := strconv.ParseInt(value, 10, 64)
		if parseErr != nil || maxBytes <= 0 {
			return Config{}, fmt.Errorf("OMNORA_UPDATE_MAX_PACKAGE_BYTES must be a positive integer")
		}
		cfg.Update.MaxPackageBytes = maxBytes
	}
	if value := strings.TrimSpace(os.Getenv("OMNORA_SQLITE_BUSY_TIMEOUT")); value != "" {
		timeout, err := time.ParseDuration(value)
		if err != nil {
			return Config{}, fmt.Errorf("OMNORA_SQLITE_BUSY_TIMEOUT: %w", err)
		}
		if timeout <= 0 {
			return Config{}, fmt.Errorf("OMNORA_SQLITE_BUSY_TIMEOUT must be positive")
		}
		cfg.Database.BusyTimeout = timeout
	}

	cfg.Initialization.Token = strings.TrimSpace(os.Getenv("OMNORA_INITIALIZATION_TOKEN"))
	cfg.Initialization.LogToken = envTruthy("OMNORA_LOG_INITIALIZATION_TOKEN")
	if value := strings.TrimSpace(os.Getenv("OMNORA_INITIALIZATION_TOKEN_TTL")); value != "" {
		ttl, err := time.ParseDuration(value)
		if err != nil {
			return Config{}, fmt.Errorf("OMNORA_INITIALIZATION_TOKEN_TTL: %w", err)
		}
		if ttl <= 0 {
			return Config{}, fmt.Errorf("OMNORA_INITIALIZATION_TOKEN_TTL must be positive")
		}
		cfg.Initialization.TTL = ttl
	}
	cfg.Secrets.TOTPEncryptionKey = strings.TrimSpace(os.Getenv("OMNORA_TOTP_ENCRYPTION_KEY"))
	cfg.Secrets.AuditHMACKey = strings.TrimSpace(os.Getenv("OMNORA_AUDIT_HMAC_KEY"))
	if value := strings.TrimSpace(os.Getenv("OMNORA_MANAGED_STORAGE_DIR")); value != "" {
		cfg.Storage.ManagedDir = value
	}
	if value := strings.TrimSpace(os.Getenv("OMNORA_PREDECLARED_MOUNT_ROOT")); value != "" {
		cfg.Storage.PredeclaredMountRoot = value
	}

	envByGroup := map[domain.RouteGroup]string{
		domain.RouteGroupMemberWeb: "OMNORA_ROUTE_MEMBER_WEB_ENABLED",
		domain.RouteGroupAdminWeb:  "OMNORA_ROUTE_ADMIN_WEB_ENABLED",
		domain.RouteGroupShare:     "OMNORA_ROUTE_SHARE_ENABLED",
		domain.RouteGroupREST:      "OMNORA_ROUTE_REST_ENABLED",
		domain.RouteGroupMCP:       "OMNORA_ROUTE_MCP_ENABLED",
		domain.RouteGroupOpenAPI:   "OMNORA_ROUTE_OPENAPI_ENABLED",
	}
	for group, name := range envByGroup {
		enabled, ok, err := parseOptionalBool(os.Getenv(name))
		if err != nil {
			return Config{}, fmt.Errorf("%s: %w", name, err)
		}
		if ok {
			cfg.Routes.Set(group, enabled)
			cfg.RouteEnvOverrides[group] = enabled
		}
	}

	return cfg, nil
}

// ValidateAuditHMACKey checks the minimum key material required for keyed
// audit identifiers. Empty is accepted while business routes are disabled so
// health and bootstrap diagnostics can still run; callers exposing those
// routes must invoke this validation before declaring the service ready.
func (cfg Config) ValidateAuditHMACKey() error {
	rawKey := cfg.Secrets.AuditHMACKey
	if strings.ContainsAny(rawKey, "\r\n") {
		return fmt.Errorf("OMNORA_AUDIT_HMAC_KEY must contain at least 32 bytes")
	}
	key := strings.TrimSpace(rawKey)
	if key == "" {
		return fmt.Errorf("OMNORA_AUDIT_HMAC_KEY is required when a business route is enabled")
	}
	if len([]byte(key)) < 32 {
		return fmt.Errorf("OMNORA_AUDIT_HMAC_KEY must contain at least 32 bytes")
	}
	return nil
}

// ValidateBusinessExposure enforces the external trust boundary only when a
// business route is exposed. Missing PublicURL returns ErrPublicURLRequired so
// operators can bring the process up first and set the public origin after the
// deployment address is known; malformed values remain hard configuration
// errors. A disabled-route configuration may omit PublicURL entirely.
func (cfg Config) ValidateBusinessExposure() error {
	exposed := false
	for _, group := range domain.AllRouteGroups {
		if group == domain.RouteGroupMemberWeb || group == domain.RouteGroupAdminWeb || group == domain.RouteGroupShare || group == domain.RouteGroupREST || group == domain.RouteGroupMCP || group == domain.RouteGroupOpenAPI {
			exposed = exposed || cfg.Routes.Enabled(group)
		}
	}
	if !exposed {
		return nil
	}
	if strings.TrimSpace(cfg.HTTP.PublicURL) == "" {
		return ErrPublicURLRequired
	}
	parsed, err := url.Parse(cfg.HTTP.PublicURL)
	if err != nil || parsed.User != nil || parsed.Host == "" || (parsed.Path != "" && parsed.Path != "/") || parsed.RawQuery != "" || parsed.Fragment != "" {
		return fmt.Errorf("OMNORA_PUBLIC_URL must be an absolute origin without path, query, or fragment")
	}
	if parsed.Scheme != "https" && parsed.Scheme != "http" {
		return fmt.Errorf("OMNORA_PUBLIC_URL scheme must be http or https")
	}
	if parsed.Scheme == "http" && !isLoopbackAuthority(parsed.Hostname()) && !cfg.HTTP.AllowInsecurePublicHTTP {
		return fmt.Errorf("http OMNORA_PUBLIC_URL is only allowed for loopback development; set OMNORA_ALLOW_INSECURE_PUBLIC_HTTP=true for disposable QA boxes")
	}
	if parsed.Scheme == "http" && !cfg.HTTP.AllowInsecurePublicHTTP {
		if listenerHost, _, splitErr := net.SplitHostPort(cfg.HTTP.Addr); splitErr == nil && !isLoopbackAuthority(listenerHost) {
			return fmt.Errorf("http OMNORA_PUBLIC_URL requires a loopback HTTP listener")
		}
	}
	return nil
}

// BusinessRoutesExposed reports whether any product route group is enabled.
func (cfg Config) BusinessRoutesExposed() bool {
	for _, group := range domain.AllRouteGroups {
		switch group {
		case domain.RouteGroupMemberWeb, domain.RouteGroupAdminWeb, domain.RouteGroupShare,
			domain.RouteGroupREST, domain.RouteGroupMCP, domain.RouteGroupOpenAPI:
			if cfg.Routes.Enabled(group) {
				return true
			}
		}
	}
	return false
}

func envTruthy(name string) bool {
	switch strings.ToLower(strings.TrimSpace(os.Getenv(name))) {
	case "1", "true", "yes", "on":
		return true
	default:
		return false
	}
}

func parseCSVEnv(name string) ([]string, error) {
	raw := strings.TrimSpace(os.Getenv(name))
	if raw == "" {
		return nil, nil
	}
	parts := strings.Split(raw, ",")
	values := make([]string, 0, len(parts))
	for _, part := range parts {
		value := strings.TrimSpace(part)
		if value == "" || strings.ContainsAny(value, "* \t\r\n") {
			return nil, fmt.Errorf("%s contains an empty or wildcard value", name)
		}
		values = append(values, value)
	}
	return values, nil
}

func parseCIDRsEnv(name string) ([]*net.IPNet, error) {
	values, err := parseCSVEnv(name)
	if err != nil {
		return nil, err
	}
	result := make([]*net.IPNet, 0, len(values))
	for _, value := range values {
		_, network, err := net.ParseCIDR(value)
		if err != nil {
			return nil, fmt.Errorf("%s contains invalid CIDR %q: %w", name, value, err)
		}
		result = append(result, network)
	}
	return result, nil
}

func isLoopbackAuthority(host string) bool {
	ip := net.ParseIP(host)
	return (ip != nil && ip.IsLoopback()) || strings.EqualFold(host, "localhost")
}

func parseOptionalBool(value string) (bool, bool, error) {
	value = strings.TrimSpace(strings.ToLower(value))
	if value == "" {
		return false, false, nil
	}

	if parsed, err := strconv.ParseBool(value); err == nil {
		return parsed, true, nil
	}

	switch value {
	case "yes", "y", "on", "enabled":
		return true, true, nil
	case "no", "n", "off", "disabled":
		return false, true, nil
	default:
		return false, true, fmt.Errorf("invalid boolean %q", value)
	}
}
